server:
  port: 8080

spring:
  application:
    name: my-meal-prep
  
  # Database configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console

# LLM Configuration
llm:
  api:
    base-url: https://api.openai.com/v1
    model: gpt-4
    timeout: 30000
    max-tokens: 1000

# Logging
logging:
  level:
    com.magistrati.mymealprepper: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 